services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: .
    #ports:
    #  - "8000:8000"
    volumes:
      - ./storage_vol:/app/storage
      - ./chroma_db_vol:/app/chroma_db
      - ./data:/app/data
    environment:
      ENVIRONMENT: prod
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  storage:
    driver: local
  chroma_db:
    driver: local
